/**
 * Title: Find the Difference
 *
 * Function: Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Numbers of Method:
 *
 * Problem Link: https://leetcode.com/problems/find-the-difference/
 */

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
const findTheDifference = function(s, t) {
  const source = [...s].sort();
  const target = [...t].sort();
  let length = target.length;

  for (let i = 0; i < length; i++) {
    if (target[i] !== source[i]) {
      return target[i];
    }
  }
};

/**
 * Use Bit operations
 * Of course we can also use the char code to add/minus to get the result
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
const findTheDifference2 = function(s, t) {
  let result = 0;
  const length = s.length;

  for (let i = 0; i < length; i++) {
    result = result ^ s.charCodeAt(i) ^ t.charCodeAt(i);
  }

  result = result ^ t.charCodeAt(length);

  return String.fromCharCode(result);
}
console.log(findTheDifference2("abcd", "eabcd"))
